# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.5"
manifest_format = "2.0"
project_hash = "aeb568dd211c14843c29c45e7a7ee43a456632f2"

[[deps.EventNotifiers]]
git-tree-sha1 = "001ee82d8251cc89633728c832d028efe9385348"
uuid = "de92ec2b-fb1f-40f8-8e84-3094df8dc533"
version = "1.0.0"

[[deps.NodeTree]]
git-tree-sha1 = "4c2fb07056ec6b0f2504ff33627f52680c63cf78"
uuid = "2904b71e-4df0-4a82-a724-4bbee9184de7"
version = "1.0.0"
